### ISSUE TITLE
如果引入了多个插件，第一个插件已经回复了内容，如何阻止第二个插件再进行回复呢，插件中可以直接阻止其他插件的回复么？

### ISSUE THREAD

**Issue by gengchen528** [wechaty/wechaty-plugin-contrib#39]

**Comment by huan** [comment]
In our current design, this can not be done easily.

The reason is that the plugin can do anything, and there's no something like [preventDefault](https://www.w3schools.com/jsref/event_preventdefault.asp) to prevent other handlers.

However, if all the plugin is written by yourself, then I believe you can make some internal communication methods between them, which I believe can help you achieve your requirement.

I'd like to link this question to:

- https://github.com/wechaty/wechaty/issues/1939#issuecomment-623053297

**Comment by gengchen528** [comment]
> In our current design, this can not be done easily.
> 
> The reason is that the plugin can do anything, and there's no something like [preventDefault](https://www.w3schools.com/jsref/event_preventdefault.asp) to prevent other handlers.
> 
> However, if all the plugin is written by yourself, then I believe you can make some internal communication methods between them, which I believe can help you achieve your requirement.
> 
> like:
> 
> ```ts
> const processedMessage = {}
> ```
> 
> Plugin A:
> 
> ```ts
> if (message.id in processedMessage) {
>   // skip
> } else {
>   processedMessage[message.id] = true
>   message.say('Im the first')
> }
> ```
> 
> Plugin B:
> 
> ```ts
> if (message.id in processedMessage) {
>   // skip
> } else {
>   processedMessage[message.id] = true
>   message.say('Im the first')
> }
> ```
> 
> I'd like to link this question to:
> 
> * [wechaty/wechaty#1939 (comment)](https://github.com/wechaty/wechaty/issues/1939#issuecomment-623053297)
好的 非常感谢，我试一下
